source/includes/_accounts.md

added documentation for account creation and update

---

source/includes/_accounts.md
source/includes/_tasks.md
source/index.html.md

added documentation for task creation and search

---

source/includes/_misc.md
source/includes/_opportunities.md

added opportunity_stages endpoint

---

source/includes/_authentication.md
source/includes/_introduction.md

add note for curl.exe users

---

source/includes/_organizations.md

https://app.asana.com/0/inbox/1198939864869551/1200071688173208/1200126162666565

Rename Enrichment To Organization Enrichment 

---

source/includes/_ratelimits.md

Asana:
https://app.asana.com/0/1200499711071404/1200428021769082/f
Before:
After:

updated rate limits doc

---

source/includes/_enrichment.md

Adding documentation for the new bulk enrichment endpoints - CURL and Python

Adding bulk enrichment to docs

---

source/includes/_enrichment.md

Update docs description

---

source/includes/_authentication.md
source/index.html.md

API Docs - Update request and signup for API key links

---

source/includes/_sequences.md

Removing extra commas from Sequences API docs

---

source/includes/_enrichment.md
source/includes/_people.md

**JIRA/PagerDuty/Sentry URL**
https://apollopde.atlassian.net/browse/THOUG-1460
**Screenshots:**

[THOUG-1460][Atul] Adding Departments, Subdepartments, Functions and Seniority in mixed people and enrich people APIs

---

source/includes/_enrichment.md
source/includes/_people.md

Before ScreenShots :
After ScreenShots :

API documentation update

---

source/includes/_enrichment.md

Akshay has approved of these changes.

[THOUG-1854] Missing fix.

---

source/includes/_introduction.md

Introduction fix.

---

source/includes/_sequences.md

https://apollopde.atlassian.net/browse/THOUG-2038

[THOUG-2038][Atul] Adding user_id to add contacts to sequence API

---

source/includes/_enrichment.md

[THOUG-2087] Add API documentation for Expose Phone-Numbers

---

source/includes/_enrichment.md

**Briefly describe what led to the creation of this PR.**
We had changed the API request params for hashed emails in this [PR](https://github.com/apolloio/leadgenie/pull/11430) but the API docs was not updated. Causing the docs to show older data which we do not support now.
https://apollopde.atlassian.net/browse/INCIDENT-2970
**Describe your changes.**
**Before/after pictures or videos.**
| Before | After |
|--------|-------|
| <img width="1792" alt="Screenshot 2023-08-16 at 8 31 18 PM" src="https://github.com/apolloio/apollo-api-docs/assets/120726098/86c19f97-6679-49e7-b523-2d41c9ef9fee"> | <img width="1792" alt="Screenshot 2023-08-16 at 8 32 38 PM" src="https://github.com/apolloio/apollo-api-docs/assets/120726098/64f77fe5-bb5f-48de-ac35-1fed518821bb"> |
| <img width="1792" …

[INCIDENT-2970][Atul] Updating the API docs for hashed emails request param change

---

README.md
source/includes/_accounts.md
source/includes/_contacts.md
source/includes/_enrichment.md
source/includes/_misc.md
source/includes/_opportunities.md
source/includes/_organizations.md
source/includes/_people.md
source/includes/_ratelimits.md
source/includes/_sequences.md
source/includes/_tasks.md
source/index.html.md

Ticket: https://apollopde.atlassian.net/browse/LD-622
Added Sentence casing for labels and text

[LD-622][Malika] Added sentence casing for api doc

---

source/includes/_contacts.md

Jira: https://apollopde.atlassian.net/browse/INCIDENT-3260
Slack Thread: https://apolloio.slack.com/archives/C02Q41PP9HC/p1695646437767089
Attempt to make it consistent with update-contact (http://localhost:4567/#update-a-contact)

[INCIDENT-3260] Add phone-number as param for create-contact

---

source/includes/_enrichment.md

Jira/Slack: 
Before /
After/
Modified the responses as well., 
https://apolloio.slack.com/archives/C03S00HTM1P/p1696506987240469?thread_ts=1696339690.371249&cid=C03S00HTM1P

[LD-813] Add LinkedIN URL Coverage for match, bulk-match

---

source/includes/_organizations.md

Jira: https://apollopde.atlassian.net/browse/LD-815

[LD-815] Addition of mixed_companies search

---

source/includes/_accounts.md
source/includes/_contacts.md

Jira: https://apollopde.atlassian.net/browse/LD-832
Slack: https://apolloio.slack.com/archives/C02Q41PP9HC/p1697579480485859

[LD-832] Update PUT request URLs for contact, account

---

source/includes/_people.md

RCE: https://www.notion.so/apolloio/RCE-API-Documentation-People-APIs-4507e2c99cdd460283978b8655635ef0
Jira: https://apollopde.atlassian.net/browse/LD-817
Slack Discussions: https://apolloio.slack.com/archives/C0616JV62QM/p1697527904956669
Before: 
After:

[LD-817] Addition of params to mixed_people/search

---

.github/PULL_REQUEST_TEMPLATE.md

NOTICKET: Add check in PR Template for testing

---

source/includes/_enrichment.md
source/includes/_organizations.md
source/includes/_people.md

https://apollopde.atlassian.net/browse/LD-883
**BEFORE**
**AFTER**

[LD-883] Documentation on pricing for search, enrichment endpoints

---

source/includes/_sequences.md

https://apollopde.atlassian.net/browse/LD-1014

[LD-1014] Update Api Docs for adding contacts to sequence

---

source/includes/_enrichment.md

[LD-923] Restricting APIs to reveal personal-emails for GDPR people

---

source/includes/_enrichment.md

https://apolloio.slack.com/archives/C08KFUHKQ/p1717640008713689?thread_ts=1717600864.563679&cid=C08KFUHKQ

more information on enrichment behaviors

---

source/includes/_accounts.md
source/includes/_contacts.md
source/includes/_organizations.md
source/includes/_people.md
source/includes/_sequences.md
source/includes/_tasks.md

([Slack](https://apolloio.slack.com/archives/C01DM13J8LU/p1721913667767259))
[(Jira)](https://apollopde.atlassian.net/browse/INCIDENT-10220?atlOrigin=eyJpIjoiZjgyMDQyNDMzNTllNGIzNjg3NjcxODNjZDgyNzY5ODgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
**-Before**
**After-**

[IN-10220] Make API Docs changes for search Use-Cases

---

README.md
source/includes/_tasks.md

[LD-1967]: Update tasks/search with correct HTTP method and per_page

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
source/includes/_authentication.md

Please take a look at the ticket for details.

LD-1928: Add OAuth as way of authentication to docs

---

CNAME

[LD-2112] Redirect to new API doc page

---

README.md

JIRA: https://apollopde.atlassian.net/browse/IE-4435
Changes:
Added deprecation message in readme
Preview:

[IE-4438] Added depreaction message in readme
